myknow/urls.py
from django.contrib import admin
from django.urls import include, path
import myknowapp.views as myviews

urlpatterns = [
    #path('', myviews.IndexView.as_view(), name='index'),
    #path('myknowapp/', include('myknowapp.urls')),
    path('', include('myknowapp.urls')),
    path('admin/', admin.site.urls),
]

myknowapp/urls.py
from django.urls import path

from . import views

# Application namespace
app_name = 'myknowapp'
urlpatterns = [

    # ex: /myknowapp/
    # (classic) function view:
    #path('', views.index, name='index'),
    # Generic view:
    path('', views.IndexView.as_view(), name='index'),
    #path('', HomePageView.as_view(), name='home'),

    #path('search/', views.search, name='search')
    path('search/', views.SearchSubmitView.as_view(), name='search'),
    path('search_results/', views.SearchResultsView.as_view(), name='search_results'),

    #path('compare/', views.compare, name='compare')
    path('compare/', views.CompareSubmitView.as_view(), name='compare'),
    path('compare_results/', views.CompareResultsView.as_view(), name='compare_results'),

    # ex: /myknowapp/5/
    # (classic) function view:
    #path('<int:entity_id>/', views.detail, name='detail'),
    # Generic view:
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),

    path('about/', views.AboutView.as_view()),


    # ex: /myknowapp/5/results/
    #path('<int:entity_id>/results/', views.results, name='results'),
    ##path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),

    # ex: /myknowapp/5/vote/
    #path('<int:entity_id>/vote/', views.vote, name='vote'),
    ##path('<int:question_id>/vote/', views.vote, name='vote'),

]

myknowapp/models.py
from django.db import models

# Create your models here.

class Entity(models.Model):

    class Meta:
        ordering = ['name']

    name = models.CharField(max_length=50, unique=True)
    abbr = models.CharField(max_length=10, blank=True, null=True)

    date_created = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    #date_created = models.DateTimeField(default=timezone.now)
    date_updated = models.DateTimeField(blank=True, null=True, auto_now=True)
    date_birth = models.DateField(blank=True, null=True)
    date_death = models.DateField(blank=True, null=True)
    #pub_date = models.DateTimeField('date published')
    #votes = models.IntegerField(default=0)

    # RELATIONSHIPS

    # - Generalization : 
    # "Mars" is_a "Planet" (superclass), and "Planet" is_a "CelestialBody"
    # Reverse : "Planet" has subclasses "Mars", "Earth", "Venus"...
    #is_a = models.ForeignKey('Entity', on_delete=models.CASCADE, related_name="subclasses", null=True)
    is_a = models.ForeignKey('self', on_delete=models.CASCADE, related_name="subclasses", blank=True, null=True)

    domain = models.ForeignKey('self', on_delete=models.SET_NULL, related_name="domain_entities", blank=True, null=True)
    is_domain = models.BooleanField(default=False)

    comment = models.TextField(blank=True, null=True)

    # - STRONG Association
    #is_linked_to = models.ForeignKey('Entity', on_delete=models.DO_NOTHING, related_name="links")
    #is_linked_to = models.ForeignKey('Entity', on_delete=models.SET_NULL, related_name="linked", null=True)
    linked_to = models.ForeignKey('self', on_delete=models.SET_NULL, related_name="linked", blank=True, null=True, help_text="STRONG link (like Earth 'turns around' Sun)")
    linked_to_direct_name = models.CharField(max_length=100, null=True, blank=True)
    linked_to_reverse_name = models.CharField(max_length=100, null=True, blank=True)

    # - Consequence/Implication
    not_me = models.BooleanField(default=False, help_text="NOT me")
    #implies = models.ForeignKey('Entity', on_delete=models.SET_NULL, related_name="consequences", null=True)
    implies = models.ForeignKey('self', on_delete=models.SET_NULL, related_name="consequences", blank=True, null=True)
    implies_not = models.BooleanField(default=False, help_text="implies NOT")

    # - Composition/Agregation:
    #is_composed_of = models.ManyToManyField('Entity', through='CompoundHasComponents', related_name='components', null=True)
    #is_composed_of = models.ManyToManyField('Entity', related_name='components', null=True)
    #is_composed_of = models.ManyToManyField('self', symmetrical=False, related_name='components', blank=True)
    # NO QTY FOR COMPONENT
    #components = models.ManyToManyField('self', symmetrical=False, related_name='compounds', blank=True)
    # COMPONENT with a quantity
    has_components = models.ManyToManyField('self', through='EntityHasComponent', symmetrical=False, related_name='iscomponentof', blank=True)

    # - WEAK Association - Symetrical links ("friend of", "synonym of", "related to"...)
    #related_to = models.ManyToManyField('self', symmetrical=True, blank=True, help_text="WEAK link (like 'is friend of', 'is synonym of', ...)")
    synonyms = models.ManyToManyField('self', symmetrical=True, blank=True)

    # - Opposite ("love"=>"hate")
    # For a symmetrical relaiton, see https://stackoverflow.com/questions/55522760/django-symmetrical-relation-onetoonefield
    # Also, https://stackoverflow.com/questions/28307964/django-symmetrical-relation
    opposite = models.OneToOneField('self', on_delete=models.SET_NULL, blank=True, null=True)

    # ATTRIBUTES with UNITS (all preceded with prefix 'a_')
    a_radius = models.CharField('Radius (km)', max_length=20, null=True, blank=True)
    a_perimeter = models.CharField('Perimeter (km)', max_length=20, null=True, blank=True)
    a_speed = models.CharField('Speed (km/s)', max_length=20, null=True, blank=True)
    a_speed_rotation = models.CharField('Rotation speed (km/h)', max_length=20, null=True, blank=True)
    a_height = models.CharField('Height (m)', max_length=20, null=True, blank=True)
    a_width = models.CharField('Width (m)', max_length=20, null=True, blank=True)
    a_length = models.CharField('Length (m)', max_length=20, null=True, blank=True)
    a_depth = models.CharField('Depth (m)', max_length=20, null=True, blank=True)
    a_wavelength = models.CharField('Wavelength (m)', max_length=20, null=True, blank=True)
    a_frequency = models.CharField('Frequency (Hz)', max_length=20, null=True, blank=True)

    # GENERAL ATTRIBUTES
    living = models.BooleanField(default=False)
    perso = models.BooleanField(default=False)

    class Meta:
        managed = True
        db_table = 'entity'
        verbose_name_plural = "entities"

    def __str__(self):
        return (str(self.name))

    def save(self, *args, **kwargs):
        # This is same as : super(Entity,self).save(*args, **kwargs)
        super().save(*args, **kwargs)  # Call the "real" save() method.
        # Opposite : makes it reflexive : A <=> B : A opposite B => B opposite A
        # => makes the "opposite" entity points to me as its own opposite
        if self.opposite:
            ''' This does not work because it's infinitely recursive... : self saves also opposite wich saves also self (which is its opposite)...
            opp = Entity.objects.get(pk=self.opposite.id)
            opp.opposite = self
            opp.save(update_fields=['opposite'])
            '''
            self.opposite.opposite = self
            super(Entity,self.opposite).save()


class EntityHasComponent(models.Model):
    qty = models.IntegerField(default=1)
    compound = models.ForeignKey(Entity, on_delete=models.CASCADE, related_name='components')
    component = models.ForeignKey(Entity, on_delete=models.CASCADE, related_name='compounds')
    #date_joined = models.DateField()
    #invite_reason = models.CharField(max_length=64)

myknowapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
#from django.views.generic import TemplateView, ListView
from django.db.models import Q

from .models import Entity
#from .forms import EntityCompareForm



class AboutView(generic.TemplateView):
    #template_name = "about.html"
    template_name = "myknowapp/about.html"

class SearchSubmitView(generic.TemplateView):
    template_name = 'myknowapp/search.html'
class SearchResultsView(generic.ListView):
    model = Entity
    template_name = 'myknowapp/search_results.html'
    #queryset = Entity.objects.filter(name__icontains='ness') #
    def get_queryset(self):
        #return Entity.objects.filter(name__icontains='ness')
        query = self.request.GET.get('q')
        #name1 = self.request.GET.get('name1')
        #name2 = self.request.GET.get('name2')
        object_list = Entity.objects.filter(
            #Q(name__icontains='ness') | Q(name__icontains='l')
            #Q(name__icontains=name1) | Q(name__icontains=name2)
            Q(name__icontains=query) | Q(comment__icontains=query)
        )
        return object_list

class CompareSubmitView(generic.TemplateView):
    template_name = 'myknowapp/compare.html'
class CompareResultsView(generic.ListView):
    model = Entity
    template_name = 'myknowapp/compare_results.html'
    context_object_name = 'entities'
    #queryset = Entity.objects.filter(name__icontains='ness') #
    def get_queryset(self):
        #return Entity.objects.filter(name__icontains='ness')
        name1 = self.request.GET.get('name1')
        name2 = self.request.GET.get('name2')
        object_list = Entity.objects.filter(
            #Q(name__icontains='ness') | Q(name__icontains='l')
            #Q(name__icontains=name1) | Q(name__icontains=name2)
            Q(name__icontains=name1) | Q(name__icontains=name2)
        )
        '''
        e1 = Entity.objects.get(name=name1)
        e2 = Entity.objects.get(name=name2)
        '''
        # entities
        return object_list
    # Pass some extra variables to the template (implication, ...)
    def get_context_data(self, **kwargs):
        entities = self.get_queryset()
        e1 = entities[0]
        e2 = entities[1]
        #attributes = ['a_speed', 'a_speed_rotation', 'a_radius', 'a_perimeter']
        # Get all not null e1 attributes
        #attributes = [a for a in e.__dict__.keys() if a.startswith('a_') and e.__dict__[a] is not None]
        e1_attributes = [a for a in e1.__dict__.keys() if a.startswith('a_') and e1.__dict__[a]]
        e2_attributes = [a for a in e2.__dict__.keys() if a.startswith('a_') and e2.__dict__[a]]
        #common_attributes = set(e_a).intersection(set(m_a))
        common_attributes = [a for a in e1_attributes if a in e2_attributes]
        comp = []
        for a in common_attributes:
            #op = '<' if float(getattr(e1,a)) < float(e2.__dict__[a]) else '>'
            op = float(getattr(e1,a)) / float(e2.__dict__[a])
            op = "{0:.2f}".format(op)
            comp.append((a, e1.__dict__[a], op, getattr(e2,a)))
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Then add new variables
        context['comp'] = comp
        #context['attributes'] = ['speed', 'speed_rotation']
        #context['e_earth'] = Entity.objects.get(name='Earth')
        return context




class IndexView(generic.ListView):
    template_name = 'myknowapp/index.html'
    context_object_name = 'latest_entity_list'

    def get_queryset(self):
        """Return the last 100 entities."""
        # latest_entity_list
        return Entity.objects.order_by('-date_created')[:100]

    # Pass some extra variables to the template (implication, ...)
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Then add new variables
        context['e_sun'] = Entity.objects.get(name='Sun')
        context['e_earth'] = Entity.objects.get(name='Earth')
        context['e_mars'] = Entity.objects.get(name='Mars')
        context['e_car'] = Entity.objects.get(name='car')
        context['e_hb'] = Entity.objects.get(name='human body')
        context['e_univ'] = Entity.objects.get(name='Universe')
        context['e_ps'] = Entity.objects.get(name='planetary system')
        context['e_ss'] = Entity.objects.get(name='Solar System')
        context['e_love'] = Entity.objects.get(name='love')
        context['e_fear'] = Entity.objects.get(name='fear')
        context['e_fe'] = Entity.objects.get(name='fruit of the Spirit')
        return context



class DetailView(generic.DetailView):
    model = Entity
    template_name = 'myknowapp/detail.html'

    # Pass some extra variables to the template (implication, ...)
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        #obj = super().get_object()
        entity = context['entity']
        # ex: "love implies NO fear"
        # ex: "NO love implies fear"
        imp = ''
        if entity.implies:
            if entity.not_me: imp = 'NO '
            imp += entity.name + ' => '
            if entity.implies_not: imp += 'NO '
            imp += entity.implies.name
        context['implication'] = imp
        return context


'''
class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'
'''

myknowapp/templates/myknowapp/about.html
<h1>toto</h1>

myknowapp/templates/myknowapp/base.html
{% load static %}

<html>
    
    <head>
        <title>MYKNOW</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    </head>
	
	<body>
	
	    <div class="page-header">
	        <h1><a href="/">MYKNOW</a></h1>
	    </div>
	
	    <div class="content container">
	        <div class="row">
	            <div class="col-md-8">
	            {% block content %}
	            {% endblock %}
	            </div>
	        </div>
	    </div>
	
	</body>
	
</html>

myknowapp/templates/myknowapp/compare.html
{% extends 'myknowapp/base.html' %}

{% block content %}

<h1>Compare 2 entities</h1>
<form action="{% url 'myknowapp:compare_results' %}" method="get">
  <input name="name1" type="text" placeholder="entity name">
  VS
  <input name="name2" type="text" placeholder="entity name">
  <p>
  <button type="submit" class="save btn btn-default">COMPARE</button>
</form>

{% endblock %}

myknowapp/templates/myknowapp/compare_old.html
    <h2>Compare 2 entities</h2>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>

myknowapp/templates/myknowapp/compare_results.html
{% extends 'myknowapp/base.html' %}

{% block content %}

<h1>Compare Results</h1>


<ul>
  {% for entity in entities %}
    <li>
      {{ entity.name }}, {{ entity.is_a }}
    </li>
  {% endfor %}
</ul>

<table>
    <thead>
        <tr>
            <th colspan="2">Comparison table</th>
        </tr>
    </thead>
    <tbody>

		<tr>
				<td></td> <td><b>{{entities.0}}</b></td> <td><b> VS </b></td> <td><b>{{entities.1}}</b></td>
        </tr>
  	{%for c in comp%}
        <tr>
				<td><b>{{c.0}}</b></td> <td>{{c.1}}</td> <td>is {{c.2}} x </td> <td>{{c.3}}</td>
        </tr>
	<!--
        <tr>
				<td><b>Speed</b></td> <td>{{entities.0.speed}}</td> <td> < </td> <td>{{entities.1.speed}}</td>
        </tr>
        <tr>
				<td><b>Rotation speed</b></td> <td>{{entities.0.speed_rotation}}</td> <td> < </td> <td>{{entities.1.speed_rotation}}</td>
        </tr>
        <tr>
				<td><b>Radius</b></td> <td>{{entities.0.radius}}</td> <td> < </td> <td>{{entities.1.radius}}</td>
        </tr>
        <tr>
				<td><b>Perimeter</b></td> <td>{{entities.0.perimeter}}</td> <td> < </td> <td>{{entities.1.perimeter}}</td>
        </tr>
	-->
  	{%endfor%}

    </tbody>
</table>

{% endblock %}

myknowapp/templates/myknowapp/detail.html
{% extends 'myknowapp/base.html' %}

{% block content %}


<!--
Au minimum :
{{entity}}
-->
<h1><u>{{ entity.name }}</u></h1>




<ul>


<li><b>Opposite: </b>
{% if entity.opposite %}
	<a href="{%url 'myknowapp:detail' entity.opposite.id%}">{{ entity.opposite.name }}</a>
{% endif %}
</li>


<li><b>Implication (consequence):</b>
{% if entity.implies %}
	<a href="{%url 'myknowapp:detail' entity.implies.id%}">{{ implication }}</a>
{% endif %}
</li>


<li><b>Is a (class):</b>
{% if entity.is_a %}
	<a href="{%url 'myknowapp:detail' entity.is_a.id%}">{{ entity.is_a.name }}</a>
{% endif %}
</li>


<li><b>Subclasses:</b>
<ul>
<!--
for subclass in entity.is_a_set.all
-->
{% for subclass in entity.subclasses.all %}
	<li><a href="{%url 'myknowapp:detail' subclass.id%}">{{ subclass.name }}</a>
	
	<ul>
	{% for subclass2 in subclass.subclasses.all %}
		<li><a href="{%url 'myknowapp:detail' subclass2.id%}">{{ subclass2.name }}</a>
	{% endfor %}
	</ul>

{% endfor %}
</ul>
</li>


<li><b>Links (strong "named" relationship):</b>
<ul>

	<!--
	<li>is related to 1 : 
	-->
	{% if entity.linked_to %}
	<li>
		{{entity.linked_to_direct_name}} : <a href="{%url 'myknowapp:detail' entity.linked_to.id%}">{{ entity.linked_to.name }}</a>
		
		{% if entity.linked_to.linked_to %}
		<ul><li>
			{{entity.linked_to.linked_to_direct_name}} : <a href="{%url 'myknowapp:detail' entity.linked_to.id%}">{{ entity.linked_to.linked_to.name }}</a>
		</li></ul>
		{% endif %}

	</li>
	{% endif %}

	<!--
	<li>is related to N :</li>
	-->
	{% if entity.linked.all.exists %}
	<li>{{entity.linked.all.first.linked_to_reverse_name}} : </li>
		<ul>
		{% for linked in entity.linked.all %}
			<li><a href="{%url 'myknowapp:detail' linked.id%}">{{ linked.name }}</a></li>
			
			{% if linked.linked.all.exists %}
			<ul>
			<li>{{linked.linked.all.first.linked_to_reverse_name}} : </li>
				<ul>
				{% for linked2 in linked.linked.all %}
					<li><a href="{%url 'myknowapp:detail' linked2.id%}">{{ linked2.name }}</a></li>
				{% endfor %}
				</ul>
			</ul>
			{% endif %}
			
		{% endfor %}
		</ul>
	{% endif %}

</ul>


<li><b>Synonyms:</b>
<ul>
{% for synonym in entity.synonyms.all %}
	<li><a href="{%url 'myknowapp:detail' synonym.id%}">{{ synonym }}</a></li>
{% endfor %}
</ul>


<li><b>Components:</b>
<ul>

{% comment "Component without quantity" %}
{% for component in entity.components.all %}
{% endcomment %}

{% comment "Component with quantity" %}
- Component only:
{% for component in entity.has_components.all %}
    <li>{{ component.name }}</li>
{% endfor %}
- Component with qty :
{% endcomment %}

{% for component in entity.components.all %}
	<!--
    <li>{{ component.qty }} {{ component.component }}</li>
	-->
	<li>{{ component.qty }} <a href="{%url 'myknowapp:detail' component.component.id%}">{{ component.component }}</a></li>
	<ul>
	{% for component2 in component.component.components.all %}
		<li>{{ component2.qty }} <a href="{%url 'myknowapp:detail' component2.component.id%}">{{ component2.component }}</a></li>
	{% endfor %}
	</ul>
{% endfor %}
</ul>


<li><b>Compounds:</b>
<ul>
{% for compound in entity.compounds.all %}
	<li><a href="{%url 'myknowapp:detail' compound.compound.id%}">{{ compound.compound }}</a></li>

		<ul>
		{% for compound2 in compound.compound.compounds.all %}
			<li><a href="{%url 'myknowapp:detail' compound2.compound.id%}">{{ compound2.compound }}</a></li>
		{% endfor %}
		</ul>

{% endfor %}
</ul>


</ul>



<b><a href="http://localhost:8000/admin/myknowapp/entity/{{ entity.id }}/change">[EDIT]</a></b>


{% endblock %}

myknowapp/templates/myknowapp/index.html
{% extends 'myknowapp/base.html' %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'myknowapp/style.css' %}">

{% block content %}

<i><a href="http://localhost:8000/admin/myknowapp/entity">(=> GO TO ADMIN SITE)</a></i>

<u><h1>ENTITIES</h1></u>

<u><h2>SEARCH:</h2></u>
    <ul>
        <li><a href="{%url 'myknowapp:search' %}">SEARCH</a></li>
        <li><a href="{%url 'myknowapp:compare' %}">COMPARE</a></li>
    </ul>


<u><h2>INTERESTING ENTITIES:</h2></u>

<p>- Compositions :
    <ul>
        <li><a href="{%url 'myknowapp:detail' e_car.id%}">{{ e_car.name }}</a></li>
        <li><a href="{%url 'myknowapp:detail' e_hb.id%}">{{ e_hb.name }}</a></li>
        <li><a href="{%url 'myknowapp:detail' e_univ.id%}">{{ e_univ.name }}</a></li>
        <li><a href="{%url 'myknowapp:detail' e_ps.id%}">{{ e_ps.name }}</a></li>
        <li><a href="{%url 'myknowapp:detail' e_ss.id%}">{{ e_ss.name }}</a></li>
        <li><a href="{%url 'myknowapp:detail' e_fe.id%}">{{ e_fe.name }}</a></li>
    </ul>

<p>- Links :
    <ul>
        <li><a href="{%url 'myknowapp:detail' e_sun.id%}">{{ e_sun.name }}</a></li>
        <li><a href="{%url 'myknowapp:detail' e_earth.id%}">{{ e_earth.name }}</a></li>
        <li><a href="{%url 'myknowapp:detail' e_mars.id%}">{{ e_mars.name }}</a></li>
    </ul>

<p>- Implications (& synonyms, oppposite...):
    <ul>
        <li><a href="{%url 'myknowapp:detail' e_love.id%}">{{ e_love.name }}</a></li>
        <li><a href="{%url 'myknowapp:detail' e_fear.id%}">{{ e_fear.name }}</a></li>
    </ul>


<u><h2>- ALL ENTITIES:</h2></u>
{% if latest_entity_list %}
    <ul>
    {% for entity in latest_entity_list|dictsort:"name"  %}
		<!-- URL harcoded
        <li><a href="/myknowapp/{{ entity.id }}/">{{ entity.name }}</a></li>
		-->
		<!-- URL NOT harcoded: use url name -->
        <li><a href="{%url 'myknowapp:detail' entity.id%}">{{ entity.name }}</a></li>
    {% endfor %}
    </ul>

	

{% else %}
    <p>No entity is available.</p>
{% endif %}


{% endblock %}

myknowapp/templates/myknowapp/search.html
{% extends 'myknowapp/base.html' %}

{% block content %}

<h1>HomePage</h1>
<form action="{% url 'myknowapp:search_results' %}" method="get">
  <input name="q" type="text" placeholder="Search...">
  <!--
  <input name="name1" type="text" placeholder="Search...">
  VS
  <input name="name2" type="text" placeholder="Search...">
  -->
</form>

{% endblock %}

myknowapp/templates/myknowapp/search_old.html
<p>Entities containing '{{query_string}}'</p> 
{% for entity in entities %}
    <div>
        <span> {{ entity.date_created }} </span>
        <a href="{% url 'detail' slug=entity.slug %}"><h2 class="page-title">{{ entity.name }}</h2></a>
        <div class="post">
            {{ entity.body|safe }}
        </div>
    </div>
{% endfor %}

myknowapp/templates/myknowapp/search_results.html
{% extends 'myknowapp/base.html' %}
{% block content %}

<h1>Search Results</h1>

<ul>
  {% for entity in object_list %}
    <li>
      {{ entity.name }}, {{ entity.is_a }}
    </li>
  {% endfor %}
</ul>

{% endblock %}